### ISSUE TITLE
wiki

### ISSUE THREAD

**Issue by avd5146** [utari/UTARI_ROSTutorials#1]
FIX the format -> https://github.com/utari/UTARI_ROSTutorials/wiki/ROS-WaypointNav_pkg-with-PR2

**Comment by X-Bar** [comment]
I believe I have fixed the formatting issues on this page. Mostly the table of contents syntax was wrong and a lot of line returns were left out. Ill keep this issue open until the next time I see it. Then If I dont hear anything back ill close it. 
Thanks for reporting this 👍   : )
